Login/Models/ClientesModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Login.Models
{
    public class ClientesModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string Telefone { get; set; }
    }
}

Login/Models/ErrorViewModel.cs
using System;

namespace Login.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Login/Models/UsuariosModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Login.Models
{
    public class UsuariosModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
    }
}

Login/Controllers/ClientesController.cs
using Login.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using System.Threading.Tasks;

namespace Login.Controllers
{
    [Authorize(AuthenticationSchemes ="CookieAuthentication")]
    public class ClientesController : Controller
    {        public IActionResult Index()
        {
            Random rand = new Random();
            List<ClientesModel> model = new List<ClientesModel>();
            for (int i = 0; i < rand.Next(20,99); i++)
            {
                ClientesModel cliente = new ClientesModel();
                cliente.CPF = rand.Next(111, 999) + "." + rand.Next(111, 999) + "." + rand.Next(111, 999) + "-" + rand.Next(11, 99);
                cliente.Nome = "Nome do Cliente " + i;
                cliente.Telefone = "16" + rand.Next(1000, 9999) + "-" + rand.Next(1000, 9999);
                cliente.Id = rand.Next(1000, 9999);
                model.Add(cliente);

            }
            return View(model);
        }
    }
}

Login/Controllers/HomeController.cs
using Login.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Login.Controllers
{
    public class HomeController : Controller
    {

        public HomeController()
        {
            
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Login/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;

namespace Login.Controllers
{
    public class LoginController : Controller
    {
        private readonly Contexto db;
        public LoginController (Contexto contexto)
        {
            db = contexto;
        }
        public IActionResult Entrar()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Entrar(string login, string senha)
        {
            Entidades.Usuario usuarioLogado =
                db.USUARIOS.Where(a => a.Login == login
                && a.Senha == senha).FirstOrDefault();
            if(usuarioLogado == null)
            {
                TempData["erro"] = "Usuario e senha invalido";
                return View();
            }

            var claims = new List<Claim>();
            claims.Add(
                new Claim(ClaimTypes.Name, usuarioLogado.Nome));
            claims.Add(
                new Claim(ClaimTypes.Sid, usuarioLogado.Id.ToString()));

            var UserIdentity = new ClaimsIdentity(claims, "Acesso");

            ClaimsPrincipal principal = new ClaimsPrincipal(UserIdentity);
            await HttpContext.SignInAsync("CookieAuthentication", principal, new AuthenticationProperties());

            return Redirect("/");
        }
        public async Task<IActionResult> Logoff()
        {
            await HttpContext.SignOutAsync("CookieAuthentication");
            ViewData["ReturnUrl"] = "/";
            return Redirect("/Login/Entrar");
        }
    }
}

Login/Controllers/UsuariosController.cs
using Login.Entidades;
using Login.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Login.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly Contexto db;

        public UsuariosController(Contexto contexto)
        {
            db = contexto;
        }

        public IActionResult Index()
        {
            return View(db.USUARIOS.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Usuario dadosTela)
        {
            db.USUARIOS.Add(dadosTela);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Login/Views/Clientes/Index.cshtml
@model IEnumerable<Login.Models.ClientesModel>

@{
    ViewData["Title"] = "Index";
}
<a href="/Login/Logoff">Sair do Sistema</a>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CPF)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CPF)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
              
            </td>
        </tr>
}
    </tbody>
</table>

Login/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <div class="row">
        <div class="col-3">
            <a href="/Login/Entrar" class="btn btn-light">Login</a>
        </div>
        <div class="col-3">
            <a href="/Usuarios/Index" class="btn btn-dark">Lista de Usuários</a>
        </div>
        <div class="col-3">
            <a href="/Clientes/Index" class="btn btn-danger">Lista de Clientes</a>
        </div>
      
    </div>
</div>

Login/Views/Login/Entrar.cshtml
<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        <div class="card">
            <div class="card card-header">
                Bem Vindo ao Login
                <div class="card card-body">
                    @if (TempData["erro"] != null)
                    {
                        <div class="alert alert-danger">
                            @TempData["erro"]
                        </div>
                    }
                    <form action="/Login/Entrar" method="post">
                        <input type="text" name="login" placeholder="User" />
                        <input type="password" name="senha" placeholder="Passord" />
                        <button type="submit">Logar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Login/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Login</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Login</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Login - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Login/Views/Usuarios/Create.cshtml
@model Login.Entidades.Usuario

@{
    ViewData["Title"] = "Create";
}

<h2>Cadastrar Usuario</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
          
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
               
            </div>
            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
               
            </div>
            <div class="form-group">
                <label asp-for="Senha" class="control-label"></label>
                <input name="Senha" type="password" class="form-control" />
               
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para Lista</a>
</div>

Login/Views/Usuarios/Index.cshtml
@model IEnumerable<Login.Entidades.Usuario>

@{
    ViewData["Title"] = "Index";
}


<p>
    <a asp-action="Create">Novo Usuário</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Login)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Senha)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Login)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Senha)
            </td>
            <td>
                
            </td>
        </tr>
}
    </tbody>
</table>